from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNTIME = ROOT / "scripts" / "runtime_contract.py"
SCAFFOLD = ROOT / "scripts" / "new-html-report.sh"
HTML_VALIDATOR = ROOT / "scripts" / "validate_html_output.py"


class RuntimeContractTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.base = Path(self.temp.name)
        self.contract = self.base / "contract.json"
        self.review = self.base / "review.json"
        self.receipt = self.base / "receipt.json"
        self.action_receipt = self.base / "action-receipt.json"

    def tearDown(self) -> None:
        self.temp.cleanup()

    def run_cli(self, *args: str, expected: int = 0) -> subprocess.CompletedProcess[str]:
        completed = subprocess.run(
            [sys.executable, "-B", str(RUNTIME), *args],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(
            completed.returncode,
            expected,
            msg=f"stdout:\n{completed.stdout}\nstderr:\n{completed.stderr}",
        )
        return completed

    def init_contract(self, *extra: str) -> dict:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "news",
            "--operation", "create",
            "--channel", "artifact",
            "--source-language", "en",
            *extra,
        )
        return json.loads(self.contract.read_text(encoding="utf-8"))

    def complete_review(self) -> None:
        review = json.loads(self.review.read_text(encoding="utf-8"))
        for gate_name, gate in review["checks"].items():
            gate["status"] = "pass"
            gate["evidence"] = f"{gate_name}: report body checked against the frozen source and stated scope."
        self.review.write_text(json.dumps(review, indent=2) + "\n", encoding="utf-8")

    def write_html(self, *, language: str, body: str) -> Path:
        path = self.base / "report.html"
        path.write_text(
            "<!-- Generated by Reader's Seat -->\n"
            "<!doctype html>\n"
            f'<html lang="{language}"><head><meta name="viewport" content="width=device-width">'
            "<title>Report</title></head><body><main><h1>Report</h1>"
            f"<p>{body}</p></main></body></html>\n",
            encoding="utf-8",
        )
        return path

    def test_source_language_and_default_html_are_locked(self) -> None:
        contract = self.init_contract()
        self.assertEqual(contract["decisions"]["output_language"], "en")
        self.assertEqual(contract["decisions"]["language_decision_source"], "source-dominant-language-default")
        self.assertEqual(contract["decisions"]["output_format"], "html")
        self.assertEqual(contract["decisions"]["format_decision_source"], "self-contained-html-default")

    def test_concrete_value_expression_gate_is_mandatory(self) -> None:
        contract = self.init_contract()
        self.assertIn("concrete-value-expression", contract["required_semantic_gates"])
        review = json.loads(self.review.read_text(encoding="utf-8"))
        self.assertEqual(review["checks"]["concrete-value-expression"]["status"], "pending")

    def test_source_snapshot_derives_language_and_hash(self) -> None:
        source = self.base / "source.txt"
        source.write_text(
            "This official article explains model pricing, prompt caching, context management, "
            "and practical ways to reduce unnecessary token use in long coding sessions. " * 4,
            encoding="utf-8",
        )
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "news",
            "--operation", "create",
            "--channel", "artifact",
            "--source-file", str(source),
        )
        contract = json.loads(self.contract.read_text(encoding="utf-8"))
        self.assertEqual(contract["decisions"]["source_language"], "en")
        self.assertEqual(contract["decisions"]["output_language"], "en")
        self.assertEqual(len(contract["decisions"]["source_snapshot"]["sha256"]), 64)

    def test_declared_language_cannot_override_snapshot(self) -> None:
        source = self.base / "source.txt"
        source.write_text(
            "This is an English source article with enough substantive prose for deterministic "
            "language detection and a stable output-language decision. " * 4,
            encoding="utf-8",
        )
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "news",
            "--operation", "create",
            "--channel", "artifact",
            "--source-file", str(source),
            "--source-language", "zh",
            expected=2,
        )

    def test_source_snapshot_cannot_change_after_lock(self) -> None:
        source = self.base / "source.txt"
        source.write_text(
            "This source is frozen before drafting so later evidence checks use the same text. " * 5,
            encoding="utf-8",
        )
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "news",
            "--operation", "create",
            "--channel", "artifact",
            "--source-file", str(source),
        )
        source.write_text("The source changed after the decision lock. " * 5, encoding="utf-8")
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "publish",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
            expected=2,
        )

    def test_explicit_language_override_wins(self) -> None:
        contract = self.init_contract("--language-override", "zh-CN")
        self.assertEqual(contract["decisions"]["output_language"], "zh-cn")
        self.assertEqual(contract["decisions"]["language_decision_source"], "explicit-user-language-override")

    def test_conflicting_selected_language_is_rejected(self) -> None:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "news",
            "--operation", "create",
            "--channel", "artifact",
            "--source-language", "en",
            "--selected-language", "zh",
            expected=2,
        )

    def test_feishu_publication_requires_explicit_authorization(self) -> None:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "business",
            "--operation", "create",
            "--channel", "artifact",
            "--source-language", "zh",
            "--explicit-format", "feishu",
            "--publication-target", "feishu",
            expected=2,
        )

    def test_publish_action_uses_locked_target_and_evidence(self) -> None:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "business",
            "--operation", "create",
            "--channel", "artifact",
            "--source-language", "zh",
            "--explicit-format", "feishu",
            "--publication-target", "feishu",
            "--external-action", "publish",
            "--external-action-authorized",
            "--authorization-evidence", "User requested a new Feishu document",
        )
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "publish",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
        )
        action_receipt = json.loads(self.action_receipt.read_text(encoding="utf-8"))
        self.assertEqual(action_receipt["status"], "pass")
        self.assertEqual(action_receipt["action"], "publish")

    def test_external_action_cannot_change_after_authorization(self) -> None:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "business",
            "--operation", "rewrite",
            "--channel", "artifact",
            "--source-language", "zh",
            "--existing-format", "feishu",
            "--publication-target", "feishu",
            "--external-action", "overwrite",
            "--external-action-authorized",
            "--authorization-evidence", "User requested overwriting the named Feishu document",
        )
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "publish",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
            expected=2,
        )
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "overwrite",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
        )

    def test_external_delivery_requires_matching_action_receipt(self) -> None:
        self.run_cli(
            "init",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--scenario", "business",
            "--operation", "create",
            "--channel", "artifact",
            "--source-language", "en",
            "--explicit-format", "feishu",
            "--publication-target", "feishu",
            "--external-action", "publish",
            "--external-action-authorized",
            "--authorization-evidence", "User requested a new Feishu document",
        )
        self.complete_review()
        artifact = self.base / "feishu-export.md"
        artifact.write_text(
            "This published report contains enough English text to verify its language, "
            "format, target, and preflight action against the locked task decisions. " * 4,
            encoding="utf-8",
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "feishu",
            "--actual-publication-target", "feishu",
            "--actual-external-action", "publish",
            "--receipt", str(self.receipt),
            expected=1,
        )
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "publish",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "feishu",
            "--actual-publication-target", "feishu",
            "--actual-external-action", "publish",
            "--action-receipt", str(self.action_receipt),
            "--receipt", str(self.receipt),
        )

    def test_english_artifact_passes_only_with_complete_review(self) -> None:
        self.init_contract()
        self.complete_review()
        artifact = self.write_html(
            language="en",
            body=(
                "This report explains how prompt caching, model choice, output token pricing, "
                "and session boundaries affect the cost of a Claude Code workflow. The main "
                "recommendation is to preserve relevant context while removing unrelated history."
            ),
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--receipt", str(self.receipt),
        )
        receipt = json.loads(self.receipt.read_text(encoding="utf-8"))
        self.assertEqual(receipt["status"], "pass")

    def test_chinese_translation_of_english_source_is_blocked(self) -> None:
        self.init_contract()
        self.complete_review()
        artifact = self.write_html(
            language="zh-CN",
            body=(
                "这份报告解释提示词缓存、模型选择、输出计费和会话边界如何影响工作成本。"
                "核心建议是保留真正相关的上下文，同时清理与当前任务无关的历史信息。"
                "这样可以降低不必要的输入消耗，并让模型更专注于当前需要解决的问题。"
            ),
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--receipt", str(self.receipt),
            expected=1,
        )
        receipt = json.loads(self.receipt.read_text(encoding="utf-8"))
        self.assertEqual(receipt["status"], "fail")
        self.assertTrue(any("visible text language" in item for item in receipt["failures"]))

    def test_format_drift_is_blocked(self) -> None:
        self.init_contract()
        self.complete_review()
        artifact = self.base / "feishu-export.md"
        artifact.write_text("A sufficiently long English report body " * 12, encoding="utf-8")
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "feishu",
            "--actual-publication-target", "feishu",
            "--receipt", str(self.receipt),
            expected=1,
        )

    def test_binary_native_format_uses_extracted_content_snapshot(self) -> None:
        self.init_contract("--explicit-format", "word")
        self.complete_review()
        artifact = self.base / "report.docx"
        artifact.write_bytes(b"PK\x03\x04placeholder-docx-package")
        snapshot = self.base / "report.txt"
        snapshot.write_text(
            "This Word report contains enough extracted English prose to verify the locked "
            "language while the binary package is checked separately by its native document tool. " * 3,
            encoding="utf-8",
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--content-snapshot", str(snapshot),
            "--actual-format", "word",
            "--receipt", str(self.receipt),
        )

    def test_pending_semantic_gate_blocks_delivery(self) -> None:
        self.init_contract()
        artifact = self.write_html(
            language="en",
            body="This is a sufficiently long English report body with clear factual content. " * 5,
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--receipt", str(self.receipt),
            expected=1,
        )

    def test_high_risk_task_requires_independent_judge(self) -> None:
        contract = self.init_contract("--risk", "high")
        self.complete_review()
        artifact = self.write_html(
            language="en",
            body="This high-risk report contains enough English prose for deterministic checks. " * 5,
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--receipt", str(self.receipt),
            expected=1,
        )
        receipt = json.loads(self.receipt.read_text(encoding="utf-8"))
        self.assertIn("high-risk task is missing an independent judge result", receipt["failures"])
        self.assertEqual(contract["task"]["risk"], "high")

    def test_high_risk_task_accepts_complete_independent_judge(self) -> None:
        contract = self.init_contract("--risk", "high")
        self.complete_review()
        judge = self.base / "judge.json"
        judge.write_text(
            json.dumps({
                "schema_version": 1,
                "contract_id": contract["contract_id"],
                "verdict": "pass",
                "hard_gates": {gate: "pass" for gate in contract["required_semantic_gates"]},
            }, indent=2) + "\n",
            encoding="utf-8",
        )
        artifact = self.write_html(
            language="en",
            body="This independently reviewed report contains enough English prose to verify. " * 5,
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--judge-result", str(judge),
            "--receipt", str(self.receipt),
        )

    def test_generic_semantic_evidence_blocks_delivery(self) -> None:
        self.init_contract()
        review = json.loads(self.review.read_text(encoding="utf-8"))
        for gate in review["checks"].values():
            gate["status"] = "pass"
            gate["evidence"] = "已检查"
        self.review.write_text(json.dumps(review, indent=2) + "\n", encoding="utf-8")
        artifact = self.write_html(
            language="en",
            body="This is a sufficiently long English report body with clear factual content. " * 5,
        )
        self.run_cli(
            "verify",
            "--contract", str(self.contract),
            "--review", str(self.review),
            "--artifact", str(artifact),
            "--actual-format", "html",
            "--receipt", str(self.receipt),
            expected=1,
        )

    def test_locked_decisions_cannot_be_changed_silently(self) -> None:
        contract = self.init_contract()
        contract["decisions"]["output_language"] = "zh"
        self.contract.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8")
        self.run_cli(
            "check-action",
            "--contract", str(self.contract),
            "--action", "publish",
            "--target", "feishu",
            "--receipt", str(self.action_receipt),
            expected=2,
        )

    def test_html_scaffold_requires_locked_language(self) -> None:
        completed = subprocess.run(
            ["bash", str(SCAFFOLD), "missing-language", str(self.base)],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertNotEqual(completed.returncode, 0)
        self.assertIn("--lang", completed.stderr)

    def test_html_scaffold_writes_locked_language(self) -> None:
        completed = subprocess.run(
            ["bash", str(SCAFFOLD), "language-report", str(self.base), "--lang", "zh-CN"],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(completed.returncode, 0, completed.stderr)
        html = self.base / "language-report" / "language-report.html"
        self.assertIn('<html lang="zh-CN">', html.read_text(encoding="utf-8"))
        validation = subprocess.run(
            [
                sys.executable,
                "-B",
                str(HTML_VALIDATOR),
                str(html),
                "--scaffold",
                "--expected-language",
                "zh-CN",
            ],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(validation.returncode, 0, validation.stdout + validation.stderr)


if __name__ == "__main__":
    unittest.main()
