#!/usr/bin/env python3
"""Validate a self-contained Reader's Seat HTML artifact."""

from __future__ import annotations

import argparse
import re
import sys
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlparse


PLACEHOLDERS = (
    "Document title",
    "Replace this heading",
    "Replace this scaffold text",
    "Content goes here",
    "Report Title",
    "{{LANG}}",
)


class ArtifactParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.ids: set[str] = set()
        self.hrefs: list[str] = []
        self.assets: list[tuple[str, str]] = []
        self.tables_total = 0
        self.tables_wrapped = 0
        self.html_lang: str | None = None
        self.visible_text: list[str] = []
        self._stack: list[tuple[str, dict[str, str]]] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attributes = {key: value or "" for key, value in attrs}
        self._stack.append((tag, attributes))
        if tag == "html":
            self.html_lang = attributes.get("lang") or None
        if attributes.get("id"):
            self.ids.add(attributes["id"])
        if attributes.get("href"):
            self.hrefs.append(attributes["href"])
        for attribute in ("src", "poster"):
            if attributes.get(attribute):
                self.assets.append((tag, attributes[attribute]))
        if tag == "link" and attributes.get("href"):
            self.assets.append((tag, attributes["href"]))
        if tag == "table":
            self.tables_total += 1
            if any(
                "table-wrap" in parent_attrs.get("class", "").split()
                for _, parent_attrs in self._stack[:-1]
            ):
                self.tables_wrapped += 1

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)
        self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        for index in range(len(self._stack) - 1, -1, -1):
            if self._stack[index][0] == tag:
                del self._stack[index:]
                return

    def handle_data(self, data: str) -> None:
        excluded = {"script", "style", "noscript", "svg", "code", "pre"}
        if any(tag in excluded for tag, _ in self._stack):
            return
        self.visible_text.append(data)


def is_remote(value: str) -> bool:
    return urlparse(value).scheme in {"http", "https"}


def language_root(value: str) -> str:
    return value.strip().lower().split("-", 1)[0]


def dominant_language(text: str) -> tuple[str, int, int]:
    text = re.sub(r"https?://\S+", " ", text)
    cjk = len(re.findall(r"[\u3400-\u4dbf\u4e00-\u9fff]", text))
    latin = len(re.findall(r"[A-Za-z]", text))
    total = cjk + latin
    if total < 80:
        return "unknown", cjk, latin
    cjk_share = cjk / total
    if cjk_share >= 0.25:
        return "zh", cjk, latin
    if cjk_share <= 0.10:
        return "en", cjk, latin
    return "mixed", cjk, latin


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("html_file", type=Path)
    parser.add_argument(
        "--scaffold",
        action="store_true",
        help="allow template placeholders while checking generated structure",
    )
    parser.add_argument(
        "--expected-language",
        help="expected dominant output language, for example en or zh-CN",
    )
    args = parser.parse_args()

    html_path = args.html_file.resolve()
    errors: list[str] = []
    if not html_path.is_file():
        print(f"ERROR: file not found: {html_path}")
        return 1

    text = html_path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines or lines[0] != "<!-- Generated by Reader's Seat -->":
        errors.append("line 1 must be <!-- Generated by Reader's Seat -->")
    if '<meta name="viewport"' not in text:
        errors.append("missing viewport meta tag")
    if "<html" not in text or not re.search(r"<html\b[^>]*\blang=", text, re.IGNORECASE):
        errors.append("html element must declare lang")
    if not args.scaffold:
        for placeholder in PLACEHOLDERS:
            if placeholder in text:
                errors.append(f"unfinished scaffold placeholder: {placeholder}")

    artifact = ArtifactParser()
    artifact.feed(text)

    if args.expected_language:
        expected = language_root(args.expected_language)
        if not artifact.html_lang or language_root(artifact.html_lang) != expected:
            errors.append(
                f"html lang {artifact.html_lang!r} does not match expected language {expected}"
            )
        if not args.scaffold:
            detected, cjk, latin = dominant_language(" ".join(artifact.visible_text))
            if expected in {"en", "zh"} and detected != expected:
                errors.append(
                    f"visible text language is {detected}, expected {expected} "
                    f"(CJK={cjk}, Latin={latin})"
                )

    internal_targets = {href[1:] for href in artifact.hrefs if href.startswith("#")}
    for target in sorted(internal_targets - artifact.ids):
        errors.append(f"missing internal link target: #{target}")

    citation_refs = {
        int(match)
        for match in re.findall(r'href=["\']#cite-(\d+)["\']', text)
    }
    citation_targets = {
        int(match)
        for match in re.findall(r'id=["\']cite-(\d+)["\']', text)
    }
    for number in sorted(citation_refs - citation_targets):
        errors.append(f"citation has no source entry: cite-{number}")
    if not args.scaffold:
        for number in sorted(citation_targets - citation_refs):
            errors.append(f"source entry is not cited: cite-{number}")

    css_assets = re.findall(r"url\(\s*[\"']?([^\"')]+)", text)
    assets = artifact.assets + [("css", value.strip()) for value in css_assets]
    for tag, value in assets:
        if value.startswith("data:"):
            errors.append(f"base64/data asset is not portable: {tag} {value[:32]}")
            continue
        if is_remote(value):
            errors.append(f"remote runtime asset is forbidden: {tag} {value}")
            continue
        if value.startswith(("file://", "/")):
            errors.append(f"absolute local asset path is forbidden: {tag} {value}")
            continue
        clean = value.split("#", 1)[0].split("?", 1)[0]
        if clean and not (html_path.parent / clean).resolve().is_file():
            errors.append(f"missing local asset: {value}")

    if artifact.tables_total != artifact.tables_wrapped:
        errors.append(
            f"{artifact.tables_total - artifact.tables_wrapped} table(s) are not inside .table-wrap"
        )

    if errors:
        for error in errors:
            print(f"ERROR: {error}")
        print(f"FAIL: {len(errors)} issue(s)")
        return 1

    print(
        "PASS: "
        f"{html_path.name} | {len(artifact.assets) + len(css_assets)} assets | "
        f"{len(citation_refs)} citations | {artifact.tables_total} tables"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
